### ISSUE TITLE
[20w18a] @Inject annotation on onRender could not find any targets matching 'render' in net.minecraft.class_442

### ISSUE THREAD

**Issue by Yoghurt4C** [Siphalor/ModsOfTheWorld#1]
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [modsoftheworld.mixins.json:MainMenuScreenMixin] from phase [DEFAULT] in config [modsoftheworld.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onRender could not find any targets matching 'render' in net.minecraft.class_442. No refMap loaded. [PREINJECT Applicator Phase -> modsoftheworld.mixins.json:MainMenuScreenMixin -> Prepare Injections ->  -> handler$zbc000$onRender(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:543)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:280)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:259)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
```

**Comment by NeRdTheNed** [comment]
@Yoghurt4C should be fixed with the latest release (on curseforge)

**Comment by Siphalor** [comment]
That's long fixed and not relevant anymore lmao

**Comment by Yoghurt4C** [comment]
snusk
